name: Deploy Github Packages

on:
  release:
    types: [created]

jobs:
  deploy-github-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          version: latest
          file: dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest