name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build --build-arg LINE_ACCESS_TOKEN=${{ secrets.LINE_ACCESS_TOKEN }} --build-arg LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }} -t arjuna .
  deploy-heroku:
    runs-on: ubuntu-latest
    needs: [test-build]
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          healthcheck: https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/healthcheck
          delay: 5
          rollbackonhealthcheckfailed: true
          docker_build_args: |
            LINE_ACCESS_TOKEN
            LINE_CHANNEL_SECRET
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}