name: Deploy Heroku

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Test Image
        run: |
          docker build --no-cache -f Dockerfile.test -t arjuna-test .
  deploy-heroku:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true